const bookmyshowRoute = '/bookmyshow/'; // ! Remove This
const facebookRoute = '/facebook/'; // ! Remove This
const instagramRoute = '/instagram/';
const linkedinRoute = '/linkedin/';
const messengerRoute = '/messenger/'; // ! Remove This
const snapchatRoute = '/snapchat/';
const telegramRoute = '/telegram/';
const whatsappRoute = '/whatsapp/';
const xRoute = '/x/';
